import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Suspense } from 'react';
import { LoadingProgressBar } from '@/components/progressbar';
import { Dummy } from '@/components/dummy';

const notoSansJP400 = Noto_Sans_JP({
  weight: '400',
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansJP400.className} suppressHydrationWarning={true}>
        <Suspense fallback={<LoadingProgressBar bgColor={'bg-sky-500'} />}>
          <Dummy />
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
